# Generated by Django 3.0.7 on 2022-02-21 09:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('createRequest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='request',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Required within'),
            preserve_default=False,
        ),
    ]
