# Generated by Django 3.0.7 on 2022-02-21 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createRequest', '0002_auto_20220221_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='date',
            field=models.DateField(blank=True, verbose_name='Required within'),
        ),
        migrations.AlterField(
            model_name='request',
            name='hospital',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
