# Generated by Django 3.0.7 on 2022-02-21 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createRequest', '0003_auto_20220221_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='date',
            field=models.DateField(verbose_name='Required within'),
        ),
    ]
