# Generated by Django 3.0.7 on 2022-02-17 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=50)),
                ('dateOfBirth', models.DateField(verbose_name='Date of Birth')),
                ('lastDateOfDonation', models.DateField(verbose_name='Last Donation date')),
                ('gender', models.CharField(max_length=20)),
                ('bloodType', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=200)),
                ('isDonor', models.BooleanField()),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=30)),
                ('isAvailable', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('users', models.ManyToManyField(to='user.User')),
            ],
        ),
    ]
