# Generated by Django 3.0.7 on 2022-02-17 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disease',
            name='users',
            field=models.ManyToManyField(blank=True, to='user.User'),
        ),
    ]
