# Generated by Django 3.0.7 on 2022-02-17 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_user_isavailable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disease',
            name='users',
        ),
        migrations.AddField(
            model_name='user',
            name='diseases',
            field=models.ManyToManyField(blank=True, to='user.Disease'),
        ),
    ]
