# Generated by Django 3.0.7 on 2022-02-17 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20220218_0145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='lastDateOfDonation',
            field=models.DateTimeField(verbose_name='Last Donation date'),
        ),
    ]
