# Generated by Django 3.0.7 on 2022-02-17 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20220218_0211'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='donationCount',
            field=models.IntegerField(default=0),
        ),
    ]
